src/blog/urls.py
from django.urls import path
from .views import BlogHome, BlogPostCreate, BlogPostUpdate, BlogPostDetail, BlogPostDelete
from django.contrib.auth.decorators import login_required

app_name = "blog"

urlpatterns = [

    path('', BlogHome.as_view(), name='home'),
    path('create/', login_required(BlogPostCreate.as_view()), name='create'),
    path('<str:slug>/', BlogPostDetail.as_view(), name='post'),
    path('edit/<str:slug>', login_required(BlogPostUpdate.as_view()), name='edit'),
    path('delete/<str:slug>', login_required(BlogPostDelete.as_view()), name='delete'),
]

src/formulaire/urls.py
from django.urls import path
from formulaire.views import formulaire

app_name = "formulaire"

urlpatterns = [
    path('', formulaire, name="formulaire"),
]

src/projet1/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from .views import index, about

# auto-modif from projet1 import settings = from . import settings (utile pour l'ajout static() après urlpatterns
from . import settings

# sitemaps
from django.contrib.sitemaps.views import sitemap
from .sitemaps import BlogSitemap, IndexSitemap, AboutSitemap, BlogArticleSitemap


sitemaps = {
    'index': IndexSitemap,
    'blog': BlogSitemap,
    'about': AboutSitemap,
    'blog_article': BlogArticleSitemap,
}

# fin du sitemaps


urlpatterns = [
    path('sitemap.xml', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
    path('', index, name="index"),
    path('blog/', include('blog.urls')),
    path('formulaire/', include('formulaire.urls')),
    path('Sf23ghL250/', admin.site.urls),
    path('about/', about, name="about"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/blog/models.py
from django.contrib.auth import get_user_model
from django.template.defaultfilters import slugify
from django.db import models
from django.urls import reverse

User = get_user_model()


def get_absolute_url():
    return reverse('blog:home')


class BlogPost(models.Model):
    meta_description = models.TextField(blank=True, null=True)
    keywords = models.TextField(blank=True, null=True)
    title = models.CharField(max_length=255, unique=True, verbose_name="Titre")
    slug = models.SlugField(max_length=255, unique=True, blank=True)
    author = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    last_updated = models.DateTimeField(auto_now=True)
    created_on = models.DateField(blank=True, null=True)
    published = models.BooleanField(default=False, verbose_name="Publié")
    content = models.TextField(blank=True, verbose_name="Contenu")
    thumbnail = models.ImageField(blank=True, upload_to='mediablog')


    class Meta:
        ordering = ['-created_on']
        verbose_name = "Article"

    def __str__(self):
        return self.title

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.title)

        super().save(*args, **kwargs)

    @property
    def author_or_default(self):
        return self.author.username if self.author else "auteur inconnu"

    def get_absolute_url(self):
        return reverse('blog:home')

src/formulaire/models.py
from django.db import models

PROBLEMES = (
    ("WiFi", "Problème avec mon réseau Wifi"),
    ("Virus", "Suspicion de virus sur mon réseau"),
    ("Nettoyage", "Nettoyage de mon ordinateur"),
    ("Développement web", "Initiation au développement web"),
    ("Cours", "Cours informatique tout niveau"),
    ("Dépannage", "Dépannage informatique, problème matériel"),
    ("Récupération données", "Récupération de données"),
    ("Autre", "(Autre)"),
)

LOCALITE = (
    ("Longjumeau", "Longjumeau"),
    ("Ballainvilliers", "Ballainvilliers"),
    ("Brétigny sur Orge", "Brétigny-sur-Orge"),
    ("Longpont sur Orge", "Longpont-sur-Orge"),
    ("Villiers sur Orge", "Villiers-sur-Orge"),
    ("Savigny sur Orge", "Savigny-sur-Orge"),
    ("Epinay sur Orge", "Épinay-sur-Orge"),
    ("Ville du Bois", "Ville-du-Bois"),
    ("Nozay", "Nozay"),
    ("Linas", "Linas"),
    ("Montlhéry", "Montlhéry"),
    ("Autre", "(Autre)"),
)


class FormulaireModel(models.Model):
    Email = models.EmailField()
    Numéro_de_téléphone = models.CharField(max_length=10)
    Type = models.CharField(max_length=50, choices=PROBLEMES)
    Localité = models.CharField(null=True, max_length=50, choices=LOCALITE)
    Description = models.TextField(max_length=500)

    class Meta:
        verbose_name = "Formulaire"

src/formulaire/forms.py
from django import forms
from formulaire.models import FormulaireModel

PROBLEMES = (
    ("WiFi", "Problème avec mon réseau Wifi"),
    ("Virus", "Suspicion de virus sur mon réseau"),
    ("Nettoyage", "Nettoyage de mon ordinateur"),
    ("Développement web", "Initiation au développement web"),
    ("Cours", "Cours informatique tout niveau"),
    ("Dépannage", "Dépannage informatique, problème matériel"),
    ("Récupération données", "Récupération de données"),
    ("Autre", "(Autre)"),
)

LOCALITE = (
    ("Longjumeau", "Longjumeau"),
    ("Ballainvilliers", "Ballainvilliers"),
    ("Brétigny sur Orge", "Brétigny-sur-Orge"),
    ("Longpont sur Orge", "Longpont-sur-Orge"),
    ("Villiers sur Orge", "Villiers-sur-Orge"),
    ("Savigny sur Orge", "Savigny-sur-Orge"),
    ("Epinay sur Orge", "Épinay-sur-Orge"),
    ("Ville du Bois", "Ville-du-Bois"),
    ("Nozay", "Nozay"),
    ("Linas", "Linas"),
    ("Montlhéry", "Montlhéry"),
    ("Autre", "(Autre)"),
)


class Formulaire(forms.ModelForm):
    class Meta:
        model = FormulaireModel
        fields = [
            "Email",
            "Numéro_de_téléphone",
            "Type",
            "Localité",
            "Description",
        ]

src/blog/views.py
from django.views.generic import ListView, CreateView, UpdateView, DetailView, DeleteView
from .models import BlogPost
from django.urls import reverse_lazy


class BlogHome(ListView):
    model = BlogPost
    template_name = "../templates/blogpost_list.html"
    context_object_name = "blog"

    def get_queryset(self):
        queryset = super().get_queryset()
        if self.request.user.is_authenticated:
            return queryset

        return queryset.filter(published=True)


class BlogPostCreate(CreateView):
    model = BlogPost
    template_name = "../templates/blogpost_create.html"
    fields = ['title', 'content', ]
    success_url = reverse_lazy("blog:home")


class BlogPostUpdate(UpdateView):
    model = BlogPost
    template_name = "../templates/blogpost_edit.html"
    fields = ['title', 'content', 'published']
    success_url = reverse_lazy("blog:home")


class BlogPostDetail(DetailView):
    model = BlogPost
    template_name = "../templates/blogpost_detail.html"
    context_object_name = "post"


class BlogPostDelete(DeleteView):
    model = BlogPost
    template_name = "../templates/blogpost_confirm_delete.html"
    success_url = reverse_lazy("blog:home")

src/formulaire/views.py
from django.shortcuts import render
from formulaire.forms import Formulaire
from django.core.mail import send_mail
from django.conf import settings

def formulaire(request):
    if request.method == "POST":
        form = Formulaire(request.POST)
        if form.is_valid():
            print(form.cleaned_data)

            # Envoi de l'e-mail
            subject = "Nouvelle soumission de formulaire"
            message = "Voici les données soumises :\n" + str(form.cleaned_data)
            email_from = settings.EMAIL_HOST_USER
            recipient_list = ['contact@urgencepc91.fr', 'killian.pasche@gmail.com']
            send_mail(subject, message, email_from, recipient_list)

            form.save()
            return render(request, "../templates/réponse.html")
    else:
        form = Formulaire()

    return render(request, "../templates/formulaire.html", {"form": form})

src/projet1/views.py
from django.shortcuts import render


def index(request):
    return render(request, "../templates/index.html")


def about(request):
    return render(request, "../templates/about.html")

src/templates/about.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YNJ6R88GNY"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YNJ6R88GNY');
</script>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
	<meta name="description" content="Le professionnel du dépannage informatique en Essone.">
	<link rel="canonical" href="https://www.urgencepc91.fr">

	<title>Urgence PC 91 - Index</title>

	<link rel="shortcut icon" href="../../static/images/gt_favicon.png">

	<link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="../../static/css/bootstrap.min.css">
	<link rel="stylesheet" href="../../static/css/font-awesome.min.css">

	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="../../static/css/bootstrap-theme.css" media="screen" >
	<link rel="stylesheet" href="../../static/css/main.css">

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="../../static/js/html5shiv.js"></script>
	<script src="../../static/js/respond.min.js"></script>
	<![endif]-->
</head>

<body class="home">
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<a class="navbar-brand" href="/"><img src="../../static/images/logo.svg" alt="Progressus HTML5 template"></a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right">
					<li class="active"><a href="/">Accueil</a></li>
					<li><a href="/about">Prestations</a></li>
					<li><a href="/blog">Blog</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Liens utiles<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="https://github.com">Github</a></li>
							<li><a href="https://www.duckduckgo.com">DuckDuckGo</a></li>
							<li><a href="https://https://openai.com">OpenAI</a></li>
							<li><a href="https://getbootstratp.com">Bootstrap</a></li>
						</ul>
					</li>
					<li><a class="btn" href="/formulaire">Formulaire</a></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
	<!-- /.navbar -->

	<header id="head" class="secondary"></header>

	<!-- container -->
	<div class="container">

		<ol class="breadcrumb">
			<li><a href="/">Accueil</a></li>
			<li class="active">Prestations</li>
		</ol>

		<div class="row">

			<!-- Article main content -->
			<article class="col-sm-8 maincontent">
				<header class="page-header">
					<h1 class="page-title">Nos prestations</h1>
				</header>
				<h3>Récupération de données</h3>
				<p><img src="../../static/images/mac.jpg" alt="" class="img-rounded pull-right" width="300" ><p>Notre service de récupération de données informatiques est conçu pour aider les clients à récupérer les données importantes qui ont été perdues en raison de diverses raisons telles que la corruption du disque dur, les erreurs de système, les pannes matérielles ou logicielles, les attaques de virus, les erreurs de formatage, etc.</p>
				<p>Nous sommes équipés des outils les plus avancés et des techniques les plus récentes pour récupérer les données perdues ou endommagées à partir de n'importe quel type de périphérique de stockage de données, y compris les disques durs, les clés USB, les cartes mémoire, les serveurs, les systèmes RAID, etc. Nous sommes engagés à fournir à nos clients des solutions de récupération de données rapides et fiables pour minimiser les pertes de données et restaurer rapidement les données importantes.</p>
				<h3>Dépannage réseau</h3>
				<p>Nous proposons une prestation complète de dépannage réseau pour aider les clients à résoudre les problèmes de connectivité, les pannes réseau, les interruptions de service, les problèmes de sécurité et les erreurs de configuration. Notre équipe de techniciens qualifiés possède une expérience approfondie dans la gestion de réseaux de toutes tailles et de toutes complexités, et est en mesure d'identifier et de résoudre rapidement tout problème lié au réseau, que ce soit au niveau matériel ou logiciel. Nous sommes équipés des outils les plus récents pour diagnostiquer et résoudre les problèmes de réseau, et nous travaillons en étroite collaboration avec nos clients pour garantir une résolution rapide et efficace des problèmes. Nous sommes engagés à fournir des solutions de dépannage réseau sur mesure pour répondre aux besoins spécifiques de chaque client et pour maintenir un réseau stable et sécurisé.</p>
				<h3>Cours informatiques</h3>
				<p>Nous proposons une prestation de cours informatique complète pour aider les clients à débuter en informatique et à tirer le meilleur parti de leur équipement informatique. Cette prestation comprend des formations sur les logiciels couramment utilisés, tels que les suites bureautiques, les programmes de gestion de projet, etc. Nous offrons également des cours particuliers à des lycéens et des collégiens pour les aider à acquérir les compétences en informatique nécessaires pour réussir dans leur parcours académique. Nous sommes engagés à fournir des cours personnalisés pour répondre aux besoins individuels de chaque client, afin de garantir qu'ils puissent atteindre leurs objectifs d'apprentissage de manière efficace et efficiente.</p>
				<h3>Détéction et neutralisation de malware</h3>
				<p>La sécurité informatique est un enjeu majeur pour toutes les entreprises, car les attaques de logiciels malveillants (malware) peuvent entraîner des pertes financières et la perte de données importantes. C'est pourquoi notre entreprise propose des services de détection et de neutralisation de malware pour garantir la sécurité des systèmes informatiques de nos clients. Nous utilisons des outils sophistiqués pour identifier les menaces et nous avons une équipe d'experts en sécurité informatique qui peut rapidement répondre et neutraliser les virus détectés. Nous offrons également des conseils en matière de sécurité pour aider nos clients à prévenir les futures attaques de malware. Avec nos services de détection et de neutralisation de malware, nos clients peuvent être assurés que leur entreprise est protégée contre les menaces de sécurité informatique.</p>
				<h3>Initiation au développement web</h3>
				<p>Nous sommes également en mesure d'enseigner les concepts de base du développement web à un public novice. Vos cours sont conçus pour aider les apprenants à acquérir des compétences pratiques dans la création de sites web à partir de zéro. Vous pouvez couvrir une variété de sujets tels que l'HTML, le CSS, le JavaScript, le responsive design, la gestion de contenu et l'hébergement de sites web à l'aide du célèbre framework Django. Nous vous apprendrons comment créer des pages web, modifier les styles, ajouter des images, des vidéos et des formulaires, ainsi que des fonctionnalités interactives. Grâce à nos cours, les apprenants peuvent acquérir les connaissances nécessaires pour créer leurs propres sites web.</p>
				<h3>Tarifs</h3>
				<ul class="tableau">
					<table>
					  <tr>
						<th>Récupération de données</th>
						<th>Dépannage réseau/matériel</th>
						<th>Cours informatique</th>
					  </tr>
					  <tr>
						<td>Prix estimé, 30€ - 50€/h</td>
						<td>Prix estimé, 30€ - 50€/h</td>
						<td>Prix estimé, 40€ - 60€/h</td>
					  </tr>
					  <tr>
						<th>Nettoyage ordinateur</th>
						<th>Création site vitrine</th>
						<th>Suspicion de malware (virus)</th>
					  </tr>
					  <tr>
						<td>Prix estimé, 30€ - 50€/h</td>
						<td>Prix estimé, 90€ - 150€/h</td>
						<td>Prix estimé, 35€ - 65€/h</td>
					  </tr>
					</table>
					  <h1 style="font-size: 12px; font-style: italic;">*Estimation des prix exhaustive et calculée sans les frais de déplacements</h1>
					  <br><br><br>
				</ul>

			</aside>
			<!-- /Sidebar -->

		</div>
	</div>	<!-- /container -->



		<div class="footer2">
			<div class="container">
				<div class="row">

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav">
								<a href="/">Accueil</a> |
								<a href="/about">Prestations</a> |
								<a href="/blog">Blog</a> |
								<b><a href="/formulaire">Formulaire</a></b>
							</p>
						</div>
					</div>

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="text-right">
								Copyright &copy; 2023, propiété de <a href="mailto:contact@urgencepc91.fr">contact@urgencepc91.fr</a>
							</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>
	</footer>





	<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script src="../../static/js/headroom.min.js"></script>
	<script src="../../static/js/jQuery.headroom.min.js"></script>
	<script src="../../static/js/template.js"></script>
</body>
</html>

src/templates/base.html
<!DOCTYPE html>
<html lang="fr">
<head>
    <!-- Google tag (gtag.js) -->
<script async src="https://www.googletagmanager.com/gtag/js?id=G-YNJ6R88GNY"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'G-YNJ6R88GNY');
</script>
	<meta charset="utf-8">
	<meta name="viewport"    content="width=device-width, initial-scale=1.0">
    <meta name="description" content="{% block meta_description %}Découvrez Django. Apprenez à construire un site de A à Z et ce même sans aucune connaissances en informatique.{% endblock %}">
    <meta name="keywords" content="Django pour débutants, Tutoriel Python, Introduction à Django, Construire un site web avec Django, Fondamentaux Python pour le web, Django modèles et vues, Bases de données avec Django, Mise en forme avec Django Templates, Authentification Django, Formulaire avec Django, Python ORM, Django URL et routage, Déploiement d'un site Django, Gestion des médias avec Django, Django Admin pour les débutants, Tests unitaires en Django, Sécurisation d'un site Django, Intégration de JavaScript avec Django, Tutoriel Django REST Framework, Créer un blog avec Django, Tutoriel e-commerce Django, Django et AJAX, Extensions et paquets Django utiles, Mise à l'échelle d'une application Django, Django et API Web, Personnalisation du look avec Bootstrap et Django, Introduction à la programmation web pour les débutants, Meilleures pratiques avec Django, Python et développement web, Démarrer avec Django en zéro connaissance, {% block keywords %}{% endblock %}">
    <link rel="canonical" href="https://www.urgencepc91.fr">


    {% block title %}
    <title>Créer un site web avec Django de A à Z.</title>
    {% endblock %}

	<link rel="shortcut icon" href="../../static/images/logo.svg">

	<link rel="stylesheet" media="screen" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
	<link rel="stylesheet" href="../../static/css/bootstrap.min.css">
	<link rel="stylesheet" href="../../static/css/font-awesome.min.css">

	<!-- Custom styles for our template -->
	<link rel="stylesheet" href="../../static/css/bootstrap-theme.css" media="screen" >
	<link rel="stylesheet" href="../../static/css/main.css">

	<!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
	<!--[if lt IE 9]>
	<script src="../../static/js/html5shiv.js"></script>
	<script src="../../static/js/respond.min.js"></script>
	<![endif]-->
</head>

<body class="home">
	<!-- Fixed navbar -->
	<div class="navbar navbar-inverse navbar-fixed-top headroom" >
		<div class="container">
			<div class="navbar-header">
				<!-- Button for smallest screens -->
				<button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse"><span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
				<a class="navbar-brand" href="/"><img src="../../static/images/logo.svg" alt="Progressus HTML5 template"></a>
			</div>
			<div class="navbar-collapse collapse">
				<ul class="nav navbar-nav pull-right">
					<li class="active"><a href="/">Accueil</a></li>
					<li><a href="/about">Prestations</a></li>
					<li><a href="/blog">Blog</a></li>
					<li class="dropdown">
						<a href="#" class="dropdown-toggle" data-toggle="dropdown">Liens utiles<b class="caret"></b></a>
						<ul class="dropdown-menu">
							<li><a href="https://github.com">Github</a></li>
							<li><a href="https://www.duckduckgo.com">DuckDuckGo</a></li>
							<li><a href="https://https://openai.com">OpenAI</a></li>
							<li><a href="https://getbootstratp.com">Bootstrap</a></li>
						</ul>
					</li>
					<li><a class="btn" href="/formulaire">Formulaire</a></li>
				</ul>
			</div><!--/.nav-collapse -->
		</div>
	</div>
	<!-- /.navbar -->
	<div class="container-content">
		{% block content %}
		{% endblock %}
	</div>

</div>	<!-- /container -->

	<!-- Social links. @TODO: replace by link/instructions in template -->
	<section id="social">
		<div class="container">
			<div class="wrapper clearfix">
				<!-- AddThis Button BEGIN -->
				<div class="addthis_toolbox addthis_default_style">
				<a class="addthis_button_facebook_like" fb:like:layout="button_count"></a>
				<a class="addthis_button_tweet"></a>
				<a class="addthis_button_linkedin_counter"></a>
				<a class="addthis_button_google_plusone" g:plusone:size="medium"></a>
				</div>
				<!-- AddThis Button END -->
			</div>
		</div>
	</section>
	<!-- /social links -->


	<footer id="footer" class="top-space">



		<div class="footer2">
			<div class="container">
				<div class="row">

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="simplenav">
								<a href="/">Accueil</a> |
								<a href="/about">Prestations</a> |
								<a href="/blog">Blog</a> |
								<b><a href="/formulaire">Formulaire</a></b>
							</p>
						</div>
					</div>

					<div class="col-md-6 widget">
						<div class="widget-body">
							<p class="text-right">
								Copyright &copy; 2023, propiété de <a href="mailto:contact@urgencepc91.fr">contact@urgencepc91.fr</a>
							</p>
						</div>
					</div>

				</div> <!-- /row of widgets -->
			</div>
		</div>

	</footer>





	<!-- JavaScript libs are placed at the end of the document so the pages load faster -->
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.10.2/jquery.min.js"></script>
	<script src="https://netdna.bootstrapcdn.com/bootstrap/3.0.0/js/bootstrap.min.js"></script>
	<script src="../../static/js/headroom.min.js"></script>
	<script src="../../static/js/jQuery.headroom.min.js"></script>
	<script src="../../static/js/template.js"></script>
</body>
</html>

src/templates/blogpost_confirm_delete.html
{% extends 'base.html' %}

    {% block title %}
	<title>Supprimer un article</title>
    {% endblock %}

{% block content %}
<form method="POST">
  {% csrf_token %}
  <p>Êtes-vous sûr de vouloir supprimer "{{ post.title }}" ?</p>

  <input type="submit" value="Oui, supprimer" class="btn btn-delete">
</form>
{% endblock %}

src/templates/blogpost_create.html
{% extends 'base.html' %}

    {% block title %}
	<title>Ajouter un article</title>
    {% endblock %}

{% block content %}
  <h1 style="font-variant: small-caps ; font-size: 34px;">Ajouter un article</h1>

  <form method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Créer" class="btn btn-submit">
  </form>
{% endblock %}

src/templates/blogpost_detail.html
{% extends 'base.html' %}

    {% block meta_description %}{% if post.meta_description %}{{ post.meta_description }}{% else %}Découvrez Django. Apprenez à construire un site de A à Z et ce même sans aucune connaissances en informatique.{% endif %}{% endblock %}

    {% block keywords %}{% if post.keywords %}{{ post.keywords }}{% else %}Django pour débutants, Tutoriel Python, Introduction à Django, Construire un site web avec Django, Fondamentaux Python pour le web, Django modèles et vues, Bases de données avec Django, Mise en forme avec Django Templates, Authentification Django, Formulaire avec Django, Python ORM, Django URL et routage, Déploiement d'un site Django, Gestion des médias avec Django, Django Admin pour les débutants, Tests unitaires en Django, Sécurisation d'un site Django, Intégration de JavaScript avec Django, Tutoriel Django REST Framework, Créer un blog avec Django, Tutoriel e-commerce Django, Django et AJAX, Extensions et paquets Django utiles, Mise à l'échelle d'une application Django, Django et API Web, Personnalisation du look avec Bootstrap et Django, Introduction à la programmation web pour les débutants, Meilleures pratiques avec Django, Python et développement web, Démarrer avec Django en zéro connaissance{% endif %}{% endblock %}

    {% block title %}
    <title>{{ post.title }}</title>
    {% endblock %}

{% block content %}
  <article class="post-detail">
    <h1>{{ post.title }}</h1>
  <!-- Ajouter la boucle if / endif pour ne pas avoir d'erreur sur les articles sans images. -->
      {% if post.thumbnail %}
    <img src="{{ post.thumbnail.url }}" alt="L'image de l'article" class="post-image">
    <p style="height: 20px;"></p>
      {% endif %}
  <!-- Balise <p> utilisée pour sauter une ligne -->
    <div class="detail-detail">{{ post.content|safe|linebreaks }}</div>
    <h5 class="post-author">Publié par <i>{{ post.author_or_default }}</i> le {{ post.created_on|date:'j F Y' }}</h5>
  </article>

{% endblock %}


src/templates/blogpost_edit.html
{% extends 'base.html' %}

    {% block title %}
  	<title>Éditer un article</title>
    {% endblock %}

{% block content %}
<article class="formulaire">
  <h1>Éditer un article</h1>

  <form method="POST">
      {% csrf_token %}
      {{ form }}
  <input type="submit" value="Éditer" class="btn btn-submit">
  </form>
</article>
{% endblock %}


src/templates/blogpost_list.html
{% extends 'base.html' %}


{% block content %}
<p style="height: 5px;"></p>
<h1 style="font-size: 5rem; font-weight: bold;">Le blog de Urgence PC 91</h1>
{% for post in blog %}
<article>

    <div class="post-title">
        <h2>{{ post.title }}</h2>


    </div>


    <!-- Gère l'affichage de l'image -->

    {% if post.thumbnail %}
    <img src="{{ post.thumbnail.url }}" alt="L'image de l'article" class="post-image">
    {% endif %}
    <!-- Gère l'affichage de l'image -->

    <p class="post-excerpt">{{ post.content|safe|truncatewords:80 }}</p>
    <h5 style="font-weight: bold; font-size: 12px;" class="post-author">Publié par <i>{{ post.author_or_default }}</i> le {{ post.created_on|date:'j F Y' }}</h5>

    <form action="{% url 'blog:post' slug=post.slug %}">
        <button class="btn btn-submit">Lire l'article</button>
    </form>


    {% if request.user.is_authenticated %}
    <div>
        <a href="{% url 'blog:edit' slug=post.slug %}" class="btn-edit">Éditer</a>
        <a href="{% url 'blog:delete' slug=post.slug %}" class="btn-delete">Supprimer</a>
    </div>
    {% endif %}
    <p style="height: 60px;"></p>

</article>
{% endfor %}

{% endblock %}


src/templates/réponse.html
{% extends 'base.html' %}

    {% block title %}
    <title>Formulaire réponse</title>
    {% endblock %}

{% block content %}
    <div class="réponse">
        <h1 style="font-size: 34px; color:#333333">Formulaire de demande d'assistance.</h1>
        <p style="height: 20px;"></p>
        <h2>Votre demande a bien été prise en compte, vous serez recontacté ultérieurement !</h2>
    </div>
{% endblock %}
